[package]
name = "helibot"
version = "0.2.0"
edition = "2021"

[dependencies]
serenity = "0.12.5"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "mysql", "time"] }
tokio = { version = "1.53", features = ["macros", "rt-multi-thread", "signal", "time"] }
time = "0.3"

serde = { version = "1.0", features = ["derive"] }
config = "0.15"
dotenvy = "0.15"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
